apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-repo-demo
  annotations:
    github.com/project-slug: carlosthe19916/backstage-repo-demo
spec:
  type: other
  lifecycle: unknown
  owner: my-group
